ID_USUARIO = 1
OTRO_ID_USUARIO = 2
NOMBRE_USUARIO = "Roberto"
OTRO_NOMBRE_USUARIO = "Carlos"
APELLIDO_USUARIO = "Perez"
EMAIL_USUARIO = "roberto@gmail.com"
OTRO_EMAIL_USUARIO = "rperez@gmail.com"
CLAVE_USUARIO = "123456"
OTRA_CLAVE_USUARIO = "123"
FECHA_NACIMIENTO_USUARIO = 9/17/2000
OTRA_CLAVE_USUARIO = "654321"
OTRO_APELLIDO_USUARIO = "Rodriguez"

ARTICULO_UID = 1
OTRO_ARTICULO_UID = 2
TITULO_ARTICULO = "Sofa Antiguo"
DESCRIPCION_ARTICULO = "Un sofa de principios de siglo."
VALUACION_ARTICULO = 15000
OTRO_TITULO_ARTICULO = "Reloj de Arena"
OTRA_DESCRIPCION_ARTICULO = "Un reloj de arena que atrasa."
OTRA_VALUACION_ARTICULO = 3000

SUBASTA_UID = 1
OTRA_SUBASTA_UID = 17
TITULO_SUBASTA = "Subasta!"
DESCRIPCION_SUBASTA = "Nos vemos en la subasta!"
IMAGEN_SUBASTA = "gransubasta.jpg"
FECHA_DE_SUBASTA = 9/17/2000
OTRO_TITULO_SUBASTA = "Otra gran barata!"
OTRA_DESCRIPCION_SUBASTA = "Nos vemos la próxima semana!"
OTRA_IMAGEN_SUBASTA = "barata.gif"
OTRA_FECHA_SUBASTA = 9/23/2000

LOTE_UID = 1
OTRO_LOTE_UID = 2
BASE_LOTE = 100
ORDEN_LOTE = 1
MONTO_PUJA = 500
OTRO_MONTO_PUJA = 600
PUJA_UID = 1
OTRO_ORDEN_LOTE = 2
OTRA_BASE_LOTE = 5000
OTRA_PUJA_UID = 2

ASUNTO_MENSAJE = "asunto corto"
TEXTO_MENSAJE = "texto largo"
